/* =========================================================
   잉글리시랭크 — 학년별 이야기(스토리) 콘텐츠
   - 문장/단어는 직접 작성한 정적 데이터 (실행 중 AI 호출 없음)
   - 퀴즈 문제는 이 데이터에서 app.js의 엔진이 매번 다르게 생성함
   ========================================================= */

const STORIES = {
  1: [
    {
      id: 'g1_01', title: 'The Red Apple', titleKo: '빨간 사과',
      sentences: [
        { en: 'I have an apple.', ko: '나는 사과가 있어요.' },
        { en: 'The apple is red.', ko: '그 사과는 빨개요.' },
        { en: 'I like the apple.', ko: '나는 그 사과를 좋아해요.' },
      ],
      vocab: [
        { word: 'apple', ko: '사과' },
        { word: 'red', ko: '빨간' },
        { word: 'like', ko: '좋아하다' },
      ],
    },
    {
      id: 'g1_02', title: 'My Dog', titleKo: '내 강아지',
      sentences: [
        { en: 'I have a dog.', ko: '나는 강아지가 있어요.' },
        { en: 'The dog is small.', ko: '그 강아지는 작아요.' },
        { en: 'The dog can run.', ko: '그 강아지는 달릴 수 있어요.' },
      ],
      vocab: [
        { word: 'dog', ko: '강아지' },
        { word: 'small', ko: '작은' },
        { word: 'run', ko: '달리다' },
      ],
    },
    {
      id: 'g1_03', title: 'The Sun', titleKo: '해님',
      sentences: [
        { en: 'I see the sun.', ko: '나는 해를 봐요.' },
        { en: 'The sun is hot.', ko: '해는 뜨거워요.' },
        { en: 'The sun is up.', ko: '해가 떠 있어요.' },
      ],
      vocab: [
        { word: 'sun', ko: '해, 태양' },
        { word: 'hot', ko: '뜨거운' },
        { word: 'see', ko: '보다' },
      ],
    },
    {
      id: 'g1_04', title: 'A Blue Ball', titleKo: '파란 공',
      sentences: [
        { en: 'I have a ball.', ko: '나는 공이 있어요.' },
        { en: 'The ball is blue.', ko: '그 공은 파래요.' },
        { en: 'I can kick the ball.', ko: '나는 그 공을 찰 수 있어요.' },
      ],
      vocab: [
        { word: 'ball', ko: '공' },
        { word: 'blue', ko: '파란' },
        { word: 'kick', ko: '차다' },
      ],
    },
    {
      id: 'g1_05', title: 'My Family', titleKo: '우리 가족',
      sentences: [
        { en: 'This is my mom.', ko: '이분은 우리 엄마예요.' },
        { en: 'This is my dad.', ko: '이분은 우리 아빠예요.' },
        { en: 'I love my family.', ko: '나는 우리 가족을 사랑해요.' },
      ],
      vocab: [
        { word: 'mom', ko: '엄마' },
        { word: 'dad', ko: '아빠' },
        { word: 'love', ko: '사랑하다' },
      ],
    },
    {
      id: 'g1_06', title: 'My Toy Car', titleKo: '내 장난감 자동차',
      sentences: [
        { en: 'I have a toy car.', ko: '나는 장난감 자동차가 있어요.' },
        { en: 'The car is fast.', ko: '그 자동차는 빨라요.' },
        { en: 'I push the car.', ko: '나는 자동차를 밀어요.' },
      ],
      vocab: [
        { word: 'car', ko: '자동차' },
        { word: 'fast', ko: '빠른' },
        { word: 'push', ko: '밀다' },
      ],
    },
    {
      id: 'g1_07', title: 'The Moon', titleKo: '달',
      sentences: [
        { en: 'I see the moon.', ko: '나는 달을 봐요.' },
        { en: 'The moon is white.', ko: '달은 하얘요.' },
        { en: 'The moon is out at night.', ko: '달은 밤에 떠요.' },
      ],
      vocab: [
        { word: 'moon', ko: '달' },
        { word: 'white', ko: '하얀' },
        { word: 'night', ko: '밤' },
      ],
    },
    {
      id: 'g1_08', title: 'A Big Tree', titleKo: '커다란 나무',
      sentences: [
        { en: 'I see a big tree.', ko: '나는 커다란 나무를 봐요.' },
        { en: 'Birds sit in the tree.', ko: '새들이 나무에 앉아요.' },
        { en: 'I sit under the tree.', ko: '나는 나무 아래 앉아요.' },
      ],
      vocab: [
        { word: 'tree', ko: '나무' },
        { word: 'bird', ko: '새' },
        { word: 'sit', ko: '앉다' },
      ],
    },
    {
      id: 'g1_09', title: 'My Shoes', titleKo: '내 신발',
      sentences: [
        { en: 'I have new shoes.', ko: '나는 새 신발이 있어요.' },
        { en: 'My shoes are green.', ko: '내 신발은 초록색이에요.' },
        { en: 'I can walk fast.', ko: '나는 빨리 걸을 수 있어요.' },
      ],
      vocab: [
        { word: 'shoes', ko: '신발' },
        { word: 'new', ko: '새로운' },
        { word: 'walk', ko: '걷다' },
      ],
    },
    {
      id: 'g1_10', title: 'The Rainbow', titleKo: '무지개',
      sentences: [
        { en: 'I see a rainbow.', ko: '나는 무지개를 봐요.' },
        { en: 'It has many colors.', ko: '그것은 여러 색깔이 있어요.' },
        { en: 'The rainbow is pretty.', ko: '무지개는 예뻐요.' },
      ],
      vocab: [
        { word: 'rainbow', ko: '무지개' },
        { word: 'color', ko: '색깔' },
        { word: 'pretty', ko: '예쁜' },
      ],
    },
    {
      id: 'g1_11', title: 'I Can Swim', titleKo: '나는 수영할 수 있어요',
      sentences: [
        { en: 'I go to the pool.', ko: '나는 수영장에 가요.' },
        { en: 'I can swim well.', ko: '나는 수영을 잘해요.' },
        { en: 'Swimming is fun.', ko: '수영은 재미있어요.' },
      ],
      vocab: [
        { word: 'pool', ko: '수영장' },
        { word: 'swim', ko: '수영하다' },
        { word: 'well', ko: '잘' },
      ],
    },
    {
      id: 'g1_12', title: 'My Book', titleKo: '내 책',
      sentences: [
        { en: 'I have a new book.', ko: '나는 새 책이 있어요.' },
        { en: 'The book has a cat.', ko: '그 책에는 고양이가 나와요.' },
        { en: 'I read every night.', ko: '나는 매일 밤 책을 읽어요.' },
      ],
      vocab: [
        { word: 'book', ko: '책' },
        { word: 'read', ko: '읽다' },
        { word: 'every', ko: '매' },
      ],
    },
    {
      id: 'g1_13', title: 'The Little Fish', titleKo: '작은 물고기',
      sentences: [
        { en: 'I see a little fish.', ko: '나는 작은 물고기를 봐요.' },
        { en: 'The fish is orange.', ko: '그 물고기는 주황색이에요.' },
        { en: 'It swims in the water.', ko: '그것은 물속에서 헤엄쳐요.' },
      ],
      vocab: [
        { word: 'fish', ko: '물고기' },
        { word: 'orange', ko: '주황색의' },
        { word: 'water', ko: '물' },
      ],
    },
    {
      id: 'g1_14', title: 'A Happy Day', titleKo: '행복한 하루',
      sentences: [
        { en: 'Today, I feel happy.', ko: '오늘 나는 행복해요.' },
        { en: 'The sky is blue.', ko: '하늘이 파래요.' },
        { en: 'I play with my friends.', ko: '나는 친구들과 놀아요.' },
      ],
      vocab: [
        { word: 'happy', ko: '행복한' },
        { word: 'sky', ko: '하늘' },
        { word: 'play', ko: '놀다' },
      ],
    },
    {
      id: 'g1_15', title: 'My Hat', titleKo: '내 모자',
      sentences: [
        { en: 'I have a new hat.', ko: '나는 새 모자가 있어요.' },
        { en: 'My hat is yellow.', ko: '내 모자는 노란색이에요.' },
        { en: 'I wear it every day.', ko: '나는 그것을 매일 써요.' },
      ],
      vocab: [
        { word: 'hat', ko: '모자' },
        { word: 'yellow', ko: '노란' },
        { word: 'wear', ko: '입다, 쓰다' },
      ],
    },
  ],

  2: [
    {
      id: 'g2_01', title: 'My Cat', titleKo: '내 고양이',
      sentences: [
        { en: 'I have a cat.', ko: '나는 고양이가 있어요.' },
        { en: 'My cat is white.', ko: '내 고양이는 하얘요.' },
        { en: 'My cat likes milk.', ko: '내 고양이는 우유를 좋아해요.' },
        { en: 'My cat is very cute.', ko: '내 고양이는 아주 귀여워요.' },
      ],
      vocab: [
        { word: 'cat', ko: '고양이' },
        { word: 'white', ko: '하얀' },
        { word: 'milk', ko: '우유' },
        { word: 'cute', ko: '귀여운' },
      ],
    },
    {
      id: 'g2_02', title: 'A Rainy Day', titleKo: '비 오는 날',
      sentences: [
        { en: 'It is raining today.', ko: '오늘은 비가 와요.' },
        { en: 'I have a yellow umbrella.', ko: '나는 노란 우산이 있어요.' },
        { en: 'I jump in the puddles.', ko: '나는 물웅덩이에서 뛰어놀아요.' },
        { en: 'I love rainy days.', ko: '나는 비 오는 날을 좋아해요.' },
      ],
      vocab: [
        { word: 'rain', ko: '비' },
        { word: 'umbrella', ko: '우산' },
        { word: 'jump', ko: '뛰다' },
        { word: 'yellow', ko: '노란' },
      ],
    },
    {
      id: 'g2_03', title: 'The Big Ball', titleKo: '커다란 공',
      sentences: [
        { en: 'Look at the big ball.', ko: '저 큰 공을 봐요.' },
        { en: 'It is round and green.', ko: '그것은 둥글고 초록색이에요.' },
        { en: 'We play with the ball.', ko: '우리는 그 공을 가지고 놀아요.' },
        { en: 'It is a fun game.', ko: '그것은 재미있는 놀이예요.' },
      ],
      vocab: [
        { word: 'big', ko: '큰' },
        { word: 'round', ko: '둥근' },
        { word: 'green', ko: '초록색의' },
        { word: 'fun', ko: '재미있는' },
      ],
    },
    {
      id: 'g2_04', title: 'At the Zoo', titleKo: '동물원에서',
      sentences: [
        { en: 'We go to the zoo.', ko: '우리는 동물원에 가요.' },
        { en: 'I see a tall giraffe.', ko: '나는 키 큰 기린을 봐요.' },
        { en: 'The lion is very loud.', ko: '사자는 아주 시끄러워요.' },
        { en: 'I have a great day.', ko: '나는 아주 즐거운 하루를 보내요.' },
      ],
      vocab: [
        { word: 'zoo', ko: '동물원' },
        { word: 'giraffe', ko: '기린' },
        { word: 'lion', ko: '사자' },
        { word: 'loud', ko: '시끄러운' },
      ],
    },
    {
      id: 'g2_05', title: 'My Birthday', titleKo: '내 생일',
      sentences: [
        { en: 'Today is my birthday.', ko: '오늘은 내 생일이에요.' },
        { en: 'I have a big cake.', ko: '나는 큰 케이크가 있어요.' },
        { en: 'My friends sing for me.', ko: '내 친구들이 나를 위해 노래해요.' },
        { en: 'I am very happy.', ko: '나는 아주 행복해요.' },
      ],
      vocab: [
        { word: 'birthday', ko: '생일' },
        { word: 'cake', ko: '케이크' },
        { word: 'friend', ko: '친구' },
        { word: 'happy', ko: '행복한' },
      ],
    },
    {
      id: 'g2_06', title: 'The Snowman', titleKo: '눈사람',
      sentences: [
        { en: 'It snowed a lot today.', ko: '오늘 눈이 많이 왔어요.' },
        { en: 'I made a big snowman.', ko: '나는 큰 눈사람을 만들었어요.' },
        { en: 'I gave it a orange nose.', ko: '나는 그것에게 주황색 코를 줬어요.' },
        { en: 'My snowman looks very funny.', ko: '내 눈사람은 아주 웃겨 보여요.' },
      ],
      vocab: [
        { word: 'snow', ko: '눈' },
        { word: 'made', ko: '만들었다' },
        { word: 'nose', ko: '코' },
        { word: 'funny', ko: '웃긴' },
      ],
    },
    {
      id: 'g2_07', title: 'My Backpack', titleKo: '내 책가방',
      sentences: [
        { en: 'I have a new backpack.', ko: '나는 새 책가방이 있어요.' },
        { en: 'It is purple and big.', ko: '그것은 보라색이고 커요.' },
        { en: 'I put my books inside.', ko: '나는 책들을 그 안에 넣어요.' },
        { en: 'I carry it to school.', ko: '나는 그것을 학교에 메고 가요.' },
      ],
      vocab: [
        { word: 'backpack', ko: '책가방' },
        { word: 'purple', ko: '보라색의' },
        { word: 'inside', ko: '안에' },
        { word: 'carry', ko: '나르다, 메다' },
      ],
    },
    {
      id: 'g2_08', title: 'A Picnic', titleKo: '소풍',
      sentences: [
        { en: 'We went on a picnic.', ko: '우리는 소풍을 갔어요.' },
        { en: 'We sat on a blanket.', ko: '우리는 담요 위에 앉았어요.' },
        { en: 'We ate sandwiches and fruit.', ko: '우리는 샌드위치와 과일을 먹었어요.' },
        { en: 'It was a great day.', ko: '멋진 하루였어요.' },
      ],
      vocab: [
        { word: 'picnic', ko: '소풍' },
        { word: 'blanket', ko: '담요' },
        { word: 'sandwich', ko: '샌드위치' },
        { word: 'fruit', ko: '과일' },
      ],
    },
    {
      id: 'g2_09', title: 'The Playground', titleKo: '놀이터',
      sentences: [
        { en: 'I go to the playground.', ko: '나는 놀이터에 가요.' },
        { en: 'I like the tall slide.', ko: '나는 높은 미끄럼틀을 좋아해요.' },
        { en: 'My friends push the swing.', ko: '내 친구들이 그네를 밀어줘요.' },
        { en: 'We laugh and have fun.', ko: '우리는 웃으며 재미있게 놀아요.' },
      ],
      vocab: [
        { word: 'slide', ko: '미끄럼틀' },
        { word: 'swing', ko: '그네' },
        { word: 'tall', ko: '높은, 키가 큰' },
        { word: 'laugh', ko: '웃다' },
      ],
    },
    {
      id: 'g2_10', title: 'My Grandma', titleKo: '우리 할머니',
      sentences: [
        { en: 'I visit my grandma often.', ko: '나는 할머니를 자주 방문해요.' },
        { en: 'She tells me funny stories.', ko: '할머니는 나에게 재미있는 이야기를 해주세요.' },
        { en: 'She bakes sweet cookies for me.', ko: '할머니는 나를 위해 달콤한 쿠키를 구워주세요.' },
        { en: 'I love spending time with her.', ko: '나는 할머니와 시간을 보내는 것을 좋아해요.' },
      ],
      vocab: [
        { word: 'visit', ko: '방문하다' },
        { word: 'story', ko: '이야기' },
        { word: 'sweet', ko: '달콤한' },
        { word: 'spend', ko: '(시간을) 보내다' },
      ],
    },
    {
      id: 'g2_11', title: 'A New Toy', titleKo: '새 장난감',
      sentences: [
        { en: 'I got a new toy today.', ko: '나는 오늘 새 장난감을 받았어요.' },
        { en: 'It is a small robot.', ko: '그것은 작은 로봇이에요.' },
        { en: 'The robot can walk and talk.', ko: '그 로봇은 걷고 말할 수 있어요.' },
        { en: 'I play with it every day.', ko: '나는 매일 그것을 가지고 놀아요.' },
      ],
      vocab: [
        { word: 'toy', ko: '장난감' },
        { word: 'robot', ko: '로봇' },
        { word: 'small', ko: '작은' },
        { word: 'talk', ko: '말하다' },
      ],
    },
    {
      id: 'g2_12', title: 'The Farm', titleKo: '농장',
      sentences: [
        { en: 'We visited a farm yesterday.', ko: '우리는 어제 농장을 방문했어요.' },
        { en: 'I saw cows and sheep there.', ko: '나는 거기서 소와 양을 봤어요.' },
        { en: 'I fed the little chickens.', ko: '나는 작은 병아리들에게 먹이를 줬어요.' },
        { en: 'The farm smelled like fresh grass.', ko: '농장에서 신선한 풀 냄새가 났어요.' },
      ],
      vocab: [
        { word: 'farm', ko: '농장' },
        { word: 'cow', ko: '소' },
        { word: 'chicken', ko: '병아리, 닭' },
        { word: 'grass', ko: '풀' },
      ],
    },
    {
      id: 'g2_13', title: 'My Room', titleKo: '내 방',
      sentences: [
        { en: 'This is my own room.', ko: '이곳은 내 방이에요.' },
        { en: 'My bed is next to the window.', ko: '내 침대는 창문 옆에 있어요.' },
        { en: 'I keep my toys in a box.', ko: '나는 장난감을 상자에 보관해요.' },
        { en: 'I feel cozy in my room.', ko: '나는 내 방에서 아늑함을 느껴요.' },
      ],
      vocab: [
        { word: 'room', ko: '방' },
        { word: 'window', ko: '창문' },
        { word: 'box', ko: '상자' },
        { word: 'cozy', ko: '아늑한' },
      ],
    },
    {
      id: 'g2_14', title: 'A Sunny Day', titleKo: '화창한 날',
      sentences: [
        { en: 'The sun is shining brightly.', ko: '해가 밝게 빛나고 있어요.' },
        { en: 'I wear my favorite hat.', ko: '나는 내가 가장 좋아하는 모자를 써요.' },
        { en: 'I ride my bike outside.', ko: '나는 밖에서 자전거를 타요.' },
        { en: 'Sunny days make me smile.', ko: '화창한 날은 나를 웃게 해요.' },
      ],
      vocab: [
        { word: 'shine', ko: '빛나다' },
        { word: 'favorite', ko: '가장 좋아하는' },
        { word: 'bike', ko: '자전거' },
        { word: 'smile', ko: '웃다' },
      ],
    },
    {
      id: 'g2_15', title: 'The Puppy', titleKo: '강아지',
      sentences: [
        { en: 'My neighbor has a cute puppy.', ko: '우리 이웃은 귀여운 강아지가 있어요.' },
        { en: 'The puppy has soft brown fur.', ko: '그 강아지는 부드러운 갈색 털이 있어요.' },
        { en: 'It always wags its tail happily.', ko: '그것은 항상 행복하게 꼬리를 흔들어요.' },
        { en: 'I hope to play with it soon.', ko: '나는 곧 그것과 놀고 싶어요.' },
      ],
      vocab: [
        { word: 'puppy', ko: '강아지' },
        { word: 'soft', ko: '부드러운' },
        { word: 'tail', ko: '꼬리' },
        { word: 'hope', ko: '바라다' },
      ],
    },
  ],

  3: [
    {
      id: 'g3_01', title: 'A Trip to the Park', titleKo: '공원 나들이',
      sentences: [
        { en: 'On Sunday, we went to the park.', ko: '일요일에 우리는 공원에 갔어요.' },
        { en: 'The weather was warm and sunny.', ko: '날씨는 따뜻하고 화창했어요.' },
        { en: 'I rode my new bicycle there.', ko: '나는 거기서 새 자전거를 탔어요.' },
        { en: 'My sister flew a colorful kite.', ko: '내 여동생은 알록달록한 연을 날렸어요.' },
        { en: 'We had a wonderful afternoon together.', ko: '우리는 함께 멋진 오후를 보냈어요.' },
      ],
      vocab: [
        { word: 'park', ko: '공원' },
        { word: 'warm', ko: '따뜻한' },
        { word: 'bicycle', ko: '자전거' },
        { word: 'kite', ko: '연' },
        { word: 'together', ko: '함께' },
      ],
    },
    {
      id: 'g3_02', title: 'My Best Friend', titleKo: '나의 가장 친한 친구',
      sentences: [
        { en: 'Mina is my best friend.', ko: '미나는 나의 가장 친한 친구예요.' },
        { en: 'We sit next to each other.', ko: '우리는 서로 옆에 앉아요.' },
        { en: 'She is kind and very funny.', ko: '그녀는 친절하고 아주 재미있어요.' },
        { en: 'We share our lunch every day.', ko: '우리는 매일 점심을 나눠 먹어요.' },
        { en: 'I am glad to know her.', ko: '나는 그녀를 알게 되어 기뻐요.' },
      ],
      vocab: [
        { word: 'friend', ko: '친구' },
        { word: 'kind', ko: '친절한' },
        { word: 'funny', ko: '재미있는' },
        { word: 'share', ko: '나누다' },
        { word: 'glad', ko: '기쁜' },
      ],
    },
    {
      id: 'g3_03', title: 'The Little Bird', titleKo: '작은 새',
      sentences: [
        { en: 'A little bird fell from its nest.', ko: '작은 새가 둥지에서 떨어졌어요.' },
        { en: 'Its wing looked hurt and weak.', ko: '날개가 다치고 약해 보였어요.' },
        { en: 'I put it in a warm box.', ko: '나는 그것을 따뜻한 상자에 넣었어요.' },
        { en: 'After a week, the bird got better.', ko: '일주일 후, 그 새는 나아졌어요.' },
        { en: 'Then it flew away happily.', ko: '그리고 그것은 행복하게 날아갔어요.' },
      ],
      vocab: [
        { word: 'bird', ko: '새' },
        { word: 'nest', ko: '둥지' },
        { word: 'wing', ko: '날개' },
        { word: 'hurt', ko: '다친' },
        { word: 'fly', ko: '날다' },
      ],
    },
    {
      id: 'g3_04', title: 'The School Garden', titleKo: '학교 텃밭',
      sentences: [
        { en: 'Our class has a small garden.', ko: '우리 반은 작은 텃밭이 있어요.' },
        { en: 'We planted tomatoes and carrots there.', ko: '우리는 그곳에 토마토와 당근을 심었어요.' },
        { en: 'Every morning, we water the plants.', ko: '매일 아침, 우리는 식물에 물을 줘요.' },
        { en: 'The tomatoes are turning bright red.', ko: '토마토가 밝은 빨간색으로 변하고 있어요.' },
        { en: 'Soon, we can pick and eat them.', ko: '곧 우리는 그것들을 따서 먹을 수 있어요.' },
      ],
      vocab: [
        { word: 'garden', ko: '정원, 텃밭' },
        { word: 'plant', ko: '심다; 식물' },
        { word: 'water', ko: '물을 주다' },
        { word: 'tomato', ko: '토마토' },
        { word: 'pick', ko: '따다' },
      ],
    },
    {
      id: 'g3_05', title: 'Helping Mom', titleKo: '엄마 도와드리기',
      sentences: [
        { en: 'My mom looked very busy today.', ko: '오늘 엄마는 아주 바빠 보였어요.' },
        { en: 'I decided to help her clean.', ko: '나는 엄마 청소를 돕기로 했어요.' },
        { en: 'I washed the dishes carefully.', ko: '나는 조심스럽게 설거지를 했어요.' },
        { en: 'My mom smiled and thanked me.', ko: '엄마는 웃으며 나에게 고마워했어요.' },
        { en: 'It felt great to help her.', ko: '엄마를 도와드리니 기분이 좋았어요.' },
      ],
      vocab: [
        { word: 'busy', ko: '바쁜' },
        { word: 'clean', ko: '청소하다' },
        { word: 'wash', ko: '씻다' },
        { word: 'dish', ko: '접시' },
        { word: 'smile', ko: '웃다' },
      ],
    },
    {
      id: 'g3_06', title: 'The Lost Umbrella', titleKo: '잃어버린 우산',
      sentences: [
        { en: 'I left my umbrella on the bus.', ko: '나는 버스에 우산을 두고 내렸어요.' },
        { en: 'I felt sad and a little worried.', ko: '나는 슬프고 조금 걱정됐어요.' },
        { en: 'My teacher helped me call the bus company.', ko: '선생님이 버스 회사에 전화하는 것을 도와주셨어요.' },
        { en: 'The next day, I got my umbrella back.', ko: '다음 날, 나는 우산을 다시 찾았어요.' },
        { en: 'I was very thankful and relieved.', ko: '나는 아주 고맙고 안심이 됐어요.' },
      ],
      vocab: [
        { word: 'umbrella', ko: '우산' },
        { word: 'worried', ko: '걱정하는' },
        { word: 'company', ko: '회사' },
        { word: 'thankful', ko: '고마워하는' },
        { word: 'relieved', ko: '안심한' },
      ],
    },
    {
      id: 'g3_07', title: 'A Rainy Afternoon', titleKo: '비 오는 오후',
      sentences: [
        { en: 'It rained all afternoon yesterday.', ko: '어제는 오후 내내 비가 왔어요.' },
        { en: 'I could not play outside.', ko: '나는 밖에서 놀 수 없었어요.' },
        { en: 'Instead, I read books with my brother.', ko: '대신, 나는 남동생과 책을 읽었어요.' },
        { en: 'We also drew pictures of animals.', ko: '우리는 동물 그림도 그렸어요.' },
        { en: 'Rainy days can be fun too.', ko: '비 오는 날도 재미있을 수 있어요.' },
      ],
      vocab: [
        { word: 'afternoon', ko: '오후' },
        { word: 'instead', ko: '대신에' },
        { word: 'brother', ko: '남자 형제' },
        { word: 'draw', ko: '그리다' },
        { word: 'animal', ko: '동물' },
      ],
    },
    {
      id: 'g3_08', title: 'My Favorite Season', titleKo: '내가 가장 좋아하는 계절',
      sentences: [
        { en: 'My favorite season is autumn.', ko: '내가 가장 좋아하는 계절은 가을이에요.' },
        { en: 'The leaves turn red and orange.', ko: '나뭇잎이 빨갛고 주황빛으로 변해요.' },
        { en: 'The weather feels cool and nice.', ko: '날씨가 시원하고 좋게 느껴져요.' },
        { en: 'I enjoy walking through the falling leaves.', ko: '나는 떨어지는 나뭇잎 사이를 걷는 것을 즐겨요.' },
        { en: 'Autumn always makes me feel calm.', ko: '가을은 항상 나를 차분하게 만들어요.' },
      ],
      vocab: [
        { word: 'season', ko: '계절' },
        { word: 'leaf', ko: '나뭇잎' },
        { word: 'weather', ko: '날씨' },
        { word: 'enjoy', ko: '즐기다' },
        { word: 'calm', ko: '차분한' },
      ],
    },
    {
      id: 'g3_09', title: 'The Class Pet', titleKo: '학급 반려동물',
      sentences: [
        { en: 'Our class has a pet hamster.', ko: '우리 반은 반려 햄스터가 있어요.' },
        { en: 'Its name is Coco, and it is tiny.', ko: '이름은 코코이고, 아주 작아요.' },
        { en: 'Every student takes turns feeding it.', ko: '모든 학생이 돌아가며 밥을 줘요.' },
        { en: 'This week, it was finally my turn.', ko: '이번 주에, 드디어 내 차례였어요.' },
        { en: 'I felt so excited and proud.', ko: '나는 아주 신나고 뿌듯했어요.' },
      ],
      vocab: [
        { word: 'pet', ko: '반려동물' },
        { word: 'tiny', ko: '아주 작은' },
        { word: 'turn', ko: '차례' },
        { word: 'excited', ko: '신난' },
        { word: 'proud', ko: '뿌듯한' },
      ],
    },
    {
      id: 'g3_10', title: 'A Trip to the Library', titleKo: '도서관 나들이',
      sentences: [
        { en: 'On Saturday, I went to the library.', ko: '토요일에, 나는 도서관에 갔어요.' },
        { en: 'The library was quiet and very clean.', ko: '도서관은 조용하고 아주 깨끗했어요.' },
        { en: 'I found a book about space and stars.', ko: '나는 우주와 별에 관한 책을 찾았어요.' },
        { en: 'I borrowed three books to read at home.', ko: '나는 집에서 읽을 책 세 권을 빌렸어요.' },
        { en: 'Reading new books always makes me happy.', ko: '새 책을 읽는 것은 항상 나를 행복하게 해요.' },
      ],
      vocab: [
        { word: 'library', ko: '도서관' },
        { word: 'quiet', ko: '조용한' },
        { word: 'space', ko: '우주' },
        { word: 'borrow', ko: '빌리다' },
        { word: 'star', ko: '별' },
      ],
    },
    {
      id: 'g3_11', title: 'The Sandcastle', titleKo: '모래성',
      sentences: [
        { en: 'At the beach, I built a sandcastle.', ko: '해변에서, 나는 모래성을 지었어요.' },
        { en: 'I used a small bucket and shovel.', ko: '나는 작은 양동이와 삽을 사용했어요.' },
        { en: 'My castle had two tall towers.', ko: '내 성에는 높은 탑이 두 개 있었어요.' },
        { en: 'A wave came and washed it away.', ko: '파도가 와서 그것을 쓸어가 버렸어요.' },
        { en: 'I just laughed and built another one.', ko: '나는 그냥 웃고 다른 것을 지었어요.' },
      ],
      vocab: [
        { word: 'beach', ko: '해변' },
        { word: 'bucket', ko: '양동이' },
        { word: 'tower', ko: '탑' },
        { word: 'wave', ko: '파도' },
        { word: 'another', ko: '또 다른' },
      ],
    },
    {
      id: 'g3_12', title: 'My Weekend', titleKo: '나의 주말',
      sentences: [
        { en: 'Last weekend was full of fun activities.', ko: '지난 주말은 재미있는 활동들로 가득했어요.' },
        { en: 'On Saturday, I rode my bicycle in the park.', ko: '토요일에, 나는 공원에서 자전거를 탔어요.' },
        { en: 'On Sunday, my family watched a funny movie.', ko: '일요일에, 우리 가족은 재미있는 영화를 봤어요.' },
        { en: 'We also cooked dinner together in the kitchen.', ko: '우리는 부엌에서 함께 저녁도 요리했어요.' },
        { en: 'It was a relaxing and happy weekend.', ko: '편안하고 행복한 주말이었어요.' },
      ],
      vocab: [
        { word: 'activity', ko: '활동' },
        { word: 'movie', ko: '영화' },
        { word: 'cook', ko: '요리하다' },
        { word: 'together', ko: '함께' },
        { word: 'relaxing', ko: '편안한' },
      ],
    },
    {
      id: 'g3_13', title: 'The Kind Neighbor', titleKo: '친절한 이웃',
      sentences: [
        { en: 'Our neighbor, Mr. Kim, is very kind.', ko: '우리 이웃인 김 아저씨는 아주 친절해요.' },
        { en: 'He waters our plants when we travel.', ko: '그는 우리가 여행 갈 때 화분에 물을 줘요.' },
        { en: 'Last week, he fixed my broken bicycle.', ko: '지난주에, 그는 내 고장 난 자전거를 고쳐줬어요.' },
        { en: 'My mom baked cookies to thank him.', ko: '엄마는 그에게 고마움을 전하려고 쿠키를 구우셨어요.' },
        { en: 'Good neighbors make a neighborhood feel warm.', ko: '좋은 이웃은 동네를 따뜻하게 느껴지게 해요.' },
      ],
      vocab: [
        { word: 'neighbor', ko: '이웃' },
        { word: 'travel', ko: '여행하다' },
        { word: 'fix', ko: '고치다' },
        { word: 'broken', ko: '고장 난' },
        { word: 'warm', ko: '따뜻한' },
      ],
    },
    {
      id: 'g3_14', title: 'A Day Without Screens', titleKo: '화면 없는 하루',
      sentences: [
        { en: 'Yesterday, I did not use any screens.', ko: '어제, 나는 아무 화면도 사용하지 않았어요.' },
        { en: 'At first, I felt a little bored.', ko: '처음에는, 나는 조금 지루했어요.' },
        { en: 'Then, I played board games with my sister.', ko: '그러다, 나는 여동생과 보드게임을 했어요.' },
        { en: 'We also went outside to jump rope.', ko: '우리는 밖에 나가서 줄넘기도 했어요.' },
        { en: 'It turned out to be a great day.', ko: '결국 아주 좋은 하루가 되었어요.' },
      ],
      vocab: [
        { word: 'screen', ko: '화면' },
        { word: 'bored', ko: '지루한' },
        { word: 'sister', ko: '여자 형제' },
        { word: 'outside', ko: '밖에서' },
        { word: 'great', ko: '아주 좋은' },
      ],
    },
    {
      id: 'g3_15', title: 'The Music Class', titleKo: '음악 수업',
      sentences: [
        { en: 'Today, we had a special music class.', ko: '오늘, 우리는 특별한 음악 수업이 있었어요.' },
        { en: 'Our teacher taught us to play the recorder.', ko: '선생님이 우리에게 리코더 연주법을 가르쳐주셨어요.' },
        { en: 'It was hard at first, but fun.', ko: '처음에는 어려웠지만 재미있었어요.' },
        { en: 'By the end, I could play a song.', ko: '끝에는, 나는 노래 한 곡을 연주할 수 있었어요.' },
        { en: 'I want to practice more at home.', ko: '나는 집에서 더 연습하고 싶어요.' },
      ],
      vocab: [
        { word: 'special', ko: '특별한' },
        { word: 'teach', ko: '가르치다' },
        { word: 'hard', ko: '어려운' },
        { word: 'song', ko: '노래' },
        { word: 'practice', ko: '연습하다' },
      ],
    },
  ],

  4: [
    {
      id: 'g4_01', title: 'A Cold Winter Day', titleKo: '추운 겨울날',
      sentences: [
        { en: 'It snowed heavily last night.', ko: '어젯밤에 눈이 많이 내렸어요.' },
        { en: 'The whole town turned white and quiet.', ko: '마을 전체가 하얗고 조용해졌어요.' },
        { en: 'My friends and I built a snowman.', ko: '내 친구들과 나는 눈사람을 만들었어요.' },
        { en: 'We used carrots for its nose.', ko: '우리는 코 대신 당근을 사용했어요.' },
        { en: 'Our hands were cold, but we laughed a lot.', ko: '손은 시렸지만, 우리는 많이 웃었어요.' },
      ],
      vocab: [
        { word: 'snow', ko: '눈; 눈이 오다' },
        { word: 'quiet', ko: '조용한' },
        { word: 'build', ko: '만들다, 짓다' },
        { word: 'nose', ko: '코' },
        { word: 'laugh', ko: '웃다' },
      ],
    },
    {
      id: 'g4_02', title: 'The Class Election', titleKo: '학급 선거',
      sentences: [
        { en: 'Today, our class chose a new leader.', ko: '오늘, 우리 반은 새 반장을 뽑았어요.' },
        { en: 'Three students gave short speeches.', ko: '세 명의 학생이 짧은 연설을 했어요.' },
        { en: 'Jian promised to help everyone kindly.', ko: '지안이는 모두를 친절하게 돕겠다고 약속했어요.' },
        { en: 'Most students voted for her.', ko: '대부분의 학생들이 그녀에게 투표했어요.' },
        { en: 'She became our new class leader.', ko: '그녀는 우리의 새 반장이 되었어요.' },
      ],
      vocab: [
        { word: 'leader', ko: '지도자, 대표' },
        { word: 'speech', ko: '연설' },
        { word: 'promise', ko: '약속하다' },
        { word: 'vote', ko: '투표하다' },
        { word: 'become', ko: '~이 되다' },
      ],
    },
    {
      id: 'g4_03', title: 'Grandma\'s Kitchen', titleKo: '할머니의 부엌',
      sentences: [
        { en: 'I visited my grandma last weekend.', ko: '지난 주말에 나는 할머니를 찾아뵀어요.' },
        { en: 'Her kitchen smelled like sweet bread.', ko: '할머니 부엌에서 달콤한 빵 냄새가 났어요.' },
        { en: 'She taught me how to bake cookies.', ko: '할머니는 나에게 쿠키 굽는 법을 가르쳐 주셨어요.' },
        { en: 'We mixed flour, sugar, and butter together.', ko: '우리는 밀가루, 설탕, 버터를 함께 섞었어요.' },
        { en: 'The cookies tasted amazing when they were done.', ko: '다 됐을 때 쿠키 맛은 정말 훌륭했어요.' },
      ],
      vocab: [
        { word: 'kitchen', ko: '부엌' },
        { word: 'smell', ko: '냄새가 나다' },
        { word: 'bake', ko: '굽다' },
        { word: 'mix', ko: '섞다' },
        { word: 'taste', ko: '맛이 나다' },
      ],
    },
    {
      id: 'g4_04', title: 'The Field Trip', titleKo: '현장 학습',
      sentences: [
        { en: 'Our class visited a science museum yesterday.', ko: '어제 우리 반은 과학관을 방문했어요.' },
        { en: 'There were many interesting machines to see.', ko: '볼 수 있는 흥미로운 기계들이 많았어요.' },
        { en: 'I tried a robot arm experiment.', ko: '나는 로봇 팔 실험을 해봤어요.' },
        { en: 'My teacher explained how it worked.', ko: '선생님이 그것이 어떻게 작동하는지 설명해 주셨어요.' },
        { en: 'It was the best trip of the year.', ko: '그것은 올해 최고의 여행이었어요.' },
      ],
      vocab: [
        { word: 'museum', ko: '박물관' },
        { word: 'machine', ko: '기계' },
        { word: 'robot', ko: '로봇' },
        { word: 'explain', ko: '설명하다' },
        { word: 'trip', ko: '여행' },
      ],
    },
    {
      id: 'g4_05', title: 'A New Neighbor', titleKo: '새로운 이웃',
      sentences: [
        { en: 'A new family moved in next door.', ko: '새로운 가족이 옆집으로 이사왔어요.' },
        { en: 'They have a boy who is my age.', ko: '그들에게는 나와 나이가 같은 남자아이가 있어요.' },
        { en: 'His name is Junho, and he seems shy.', ko: '그의 이름은 준호인데, 수줍어 보였어요.' },
        { en: 'I invited him to play soccer with us.', ko: '나는 그를 우리와 축구하자고 초대했어요.' },
        { en: 'Now, we are becoming good friends.', ko: '이제 우리는 좋은 친구가 되어가고 있어요.' },
      ],
      vocab: [
        { word: 'neighbor', ko: '이웃' },
        { word: 'move', ko: '이사하다, 움직이다' },
        { word: 'shy', ko: '수줍은' },
        { word: 'invite', ko: '초대하다' },
        { word: 'soccer', ko: '축구' },
      ],
    },
    {
      id: 'g4_06', title: 'The Talent Show', titleKo: '장기자랑',
      sentences: [
        { en: 'Our school held a talent show last Friday.', ko: '우리 학교는 지난 금요일에 장기자랑을 열었어요.' },
        { en: 'I decided to perform a magic trick.', ko: '나는 마술을 보여주기로 결정했어요.' },
        { en: 'I practiced the trick every day for weeks.', ko: '나는 몇 주 동안 매일 그 마술을 연습했어요.' },
        { en: 'On stage, my hands were shaking a little.', ko: '무대에서, 내 손이 조금 떨렸어요.' },
        { en: 'In the end, everyone clapped and cheered loudly.', ko: '결국, 모두가 크게 박수치고 환호했어요.' },
      ],
      vocab: [
        { word: 'perform', ko: '공연하다' },
        { word: 'trick', ko: '마술, 속임수' },
        { word: 'stage', ko: '무대' },
        { word: 'shake', ko: '떨리다' },
        { word: 'cheer', ko: '환호하다' },
      ],
    },
    {
      id: 'g4_07', title: 'A Broken Toy', titleKo: '고장 난 장난감',
      sentences: [
        { en: 'My little brother broke my favorite toy robot.', ko: '내 남동생이 내가 가장 좋아하는 장난감 로봇을 망가뜨렸어요.' },
        { en: 'At first, I felt really angry at him.', ko: '처음에는, 나는 그에게 정말 화가 났어요.' },
        { en: 'He looked sorry and started to cry.', ko: '그는 미안해 보였고 울기 시작했어요.' },
        { en: 'I calmed down and decided to forgive him.', ko: '나는 진정하고 그를 용서하기로 했어요.' },
        { en: 'Together, we tried to fix the robot.', ko: '우리는 함께 그 로봇을 고치려고 했어요.' },
      ],
      vocab: [
        { word: 'break', ko: '망가뜨리다' },
        { word: 'angry', ko: '화난' },
        { word: 'sorry', ko: '미안한' },
        { word: 'calm', ko: '진정하다' },
        { word: 'forgive', ko: '용서하다' },
      ],
    },
    {
      id: 'g4_08', title: 'The Camping Trip', titleKo: '캠핑 여행',
      sentences: [
        { en: 'My family went camping near a lake.', ko: '우리 가족은 호수 근처로 캠핑을 갔어요.' },
        { en: 'We set up a tent together as a team.', ko: '우리는 팀으로 함께 텐트를 쳤어요.' },
        { en: 'At night, we cooked food over a campfire.', ko: '밤에, 우리는 모닥불 위에서 음식을 요리했어요.' },
        { en: 'We looked up and saw thousands of stars.', ko: '우리는 고개를 들어 수천 개의 별을 봤어요.' },
        { en: 'It was the most peaceful night of the year.', ko: '그것은 그 해 가장 평화로운 밤이었어요.' },
      ],
      vocab: [
        { word: 'lake', ko: '호수' },
        { word: 'tent', ko: '텐트' },
        { word: 'campfire', ko: '모닥불' },
        { word: 'thousand', ko: '천, 수천' },
        { word: 'peaceful', ko: '평화로운' },
      ],
    },
    {
      id: 'g4_09', title: 'My Favorite Subject', titleKo: '내가 가장 좋아하는 과목',
      sentences: [
        { en: 'My favorite subject at school is art.', ko: '학교에서 내가 가장 좋아하는 과목은 미술이에요.' },
        { en: 'I enjoy mixing different colors of paint.', ko: '나는 서로 다른 물감 색을 섞는 것을 즐겨요.' },
        { en: 'Last month, I painted a picture of the ocean.', ko: '지난달, 나는 바다 그림을 그렸어요.' },
        { en: 'My art teacher praised my creative idea.', ko: '미술 선생님이 내 창의적인 생각을 칭찬해 주셨어요.' },
        { en: 'Art class always makes my day better.', ko: '미술 수업은 항상 내 하루를 더 좋게 만들어요.' },
      ],
      vocab: [
        { word: 'subject', ko: '과목' },
        { word: 'paint', ko: '물감; 그리다' },
        { word: 'ocean', ko: '바다' },
        { word: 'praise', ko: '칭찬하다' },
        { word: 'creative', ko: '창의적인' },
      ],
    },
    {
      id: 'g4_10', title: 'The School Festival', titleKo: '학교 축제',
      sentences: [
        { en: 'Our school festival happens every autumn.', ko: '우리 학교 축제는 매년 가을에 열려요.' },
        { en: 'Each class prepares a special booth to sell.', ko: '각 반은 판매할 특별한 부스를 준비해요.' },
        { en: 'Our class decided to sell homemade bread.', ko: '우리 반은 수제 빵을 팔기로 했어요.' },
        { en: 'We worked hard, and the bread sold fast.', ko: '우리는 열심히 일했고, 빵은 빠르게 팔렸어요.' },
        { en: 'The festival was tiring but truly enjoyable.', ko: '축제는 힘들었지만 정말 즐거웠어요.' },
      ],
      vocab: [
        { word: 'festival', ko: '축제' },
        { word: 'prepare', ko: '준비하다' },
        { word: 'booth', ko: '부스' },
        { word: 'homemade', ko: '집에서 만든' },
        { word: 'tiring', ko: '힘든, 피곤하게 하는' },
      ],
    },
    {
      id: 'g4_11', title: 'A Kind Stranger', titleKo: '친절한 낯선 사람',
      sentences: [
        { en: 'One day, I lost my way in a big mall.', ko: '어느 날, 나는 큰 쇼핑몰에서 길을 잃었어요.' },
        { en: 'I felt scared and did not know what to do.', ko: '나는 무서웠고 무엇을 해야 할지 몰랐어요.' },
        { en: 'A kind stranger noticed my worried face.', ko: '친절한 낯선 분이 내 걱정스러운 얼굴을 알아채셨어요.' },
        { en: 'She helped me find my mother safely.', ko: '그녀는 내가 엄마를 안전하게 찾도록 도와주셨어요.' },
        { en: 'I learned that kindness can come from anyone.', ko: '나는 친절함은 누구에게서나 올 수 있다는 것을 배웠어요.' },
      ],
      vocab: [
        { word: 'stranger', ko: '낯선 사람' },
        { word: 'scared', ko: '무서운' },
        { word: 'notice', ko: '알아차리다' },
        { word: 'safely', ko: '안전하게' },
        { word: 'kindness', ko: '친절함' },
      ],
    },
    {
      id: 'g4_12', title: 'The Recycling Project', titleKo: '재활용 프로젝트',
      sentences: [
        { en: 'Our class started a special recycling project.', ko: '우리 반은 특별한 재활용 프로젝트를 시작했어요.' },
        { en: 'We collected plastic bottles from the neighborhood.', ko: '우리는 동네에서 플라스틱 병을 모았어요.' },
        { en: 'Then, we made useful things like pencil holders.', ko: '그런 다음, 우리는 연필꽂이 같은 유용한 것들을 만들었어요.' },
        { en: 'Our project helped protect the environment a little.', ko: '우리 프로젝트는 환경을 조금 보호하는 데 도움이 됐어요.' },
        { en: 'I felt proud to help our planet.', ko: '나는 우리 지구를 돕게 되어 뿌듯했어요.' },
      ],
      vocab: [
        { word: 'collect', ko: '모으다' },
        { word: 'useful', ko: '유용한' },
        { word: 'protect', ko: '보호하다' },
        { word: 'environment', ko: '환경' },
        { word: 'planet', ko: '지구, 행성' },
      ],
    },
    {
      id: 'g4_13', title: "My Pet's First Day", titleKo: '반려동물의 첫날',
      sentences: [
        { en: 'We brought home a new puppy yesterday.', ko: '우리는 어제 새 강아지를 집에 데려왔어요.' },
        { en: 'At first, the puppy seemed nervous and shy.', ko: '처음에, 그 강아지는 긴장하고 수줍어 보였어요.' },
        { en: 'I sat quietly and let it explore the house.', ko: '나는 조용히 앉아 그것이 집을 탐험하게 두었어요.' },
        { en: 'Slowly, the puppy began to trust our family.', ko: '천천히, 강아지는 우리 가족을 믿기 시작했어요.' },
        { en: 'By night, it was sleeping happily beside me.', ko: '밤이 되자, 그것은 내 옆에서 행복하게 자고 있었어요.' },
      ],
      vocab: [
        { word: 'bring', ko: '데려오다, 가져오다' },
        { word: 'nervous', ko: '긴장한' },
        { word: 'explore', ko: '탐험하다' },
        { word: 'trust', ko: '믿다' },
        { word: 'beside', ko: '옆에' },
      ],
    },
    {
      id: 'g4_14', title: 'The Rainy Match', titleKo: '비 오는 날의 경기',
      sentences: [
        { en: 'It started raining during our soccer match.', ko: '우리 축구 경기 도중 비가 내리기 시작했어요.' },
        { en: 'Our shoes and clothes got completely wet.', ko: '우리 신발과 옷이 완전히 젖었어요.' },
        { en: 'Still, our team kept playing with great energy.', ko: '그래도, 우리 팀은 대단한 힘으로 계속 경기했어요.' },
        { en: 'In the last minute, I scored the winning goal.', ko: '마지막 순간에, 나는 결승골을 넣었어요.' },
        { en: 'We celebrated together in the pouring rain.', ko: '우리는 쏟아지는 빗속에서 함께 축하했어요.' },
      ],
      vocab: [
        { word: 'match', ko: '경기' },
        { word: 'wet', ko: '젖은' },
        { word: 'energy', ko: '에너지, 힘' },
        { word: 'score', ko: '득점하다' },
        { word: 'celebrate', ko: '축하하다' },
      ],
    },
    {
      id: 'g4_15', title: 'A Special Gift', titleKo: '특별한 선물',
      sentences: [
        { en: 'For my birthday, my father made me a gift.', ko: '내 생일에, 아빠가 나에게 선물을 만들어주셨어요.' },
        { en: 'It was a wooden box with my name on it.', ko: '그것은 내 이름이 적힌 나무 상자였어요.' },
        { en: 'He worked on it quietly for two weeks.', ko: '그는 2주 동안 조용히 그것을 만드셨어요.' },
        { en: 'I was surprised because it was so beautiful.', ko: '나는 그것이 너무 아름다워서 놀랐어요.' },
        { en: 'Handmade gifts feel more special than anything else.', ko: '손수 만든 선물은 다른 무엇보다 더 특별하게 느껴져요.' },
      ],
      vocab: [
        { word: 'gift', ko: '선물' },
        { word: 'wooden', ko: '나무로 된' },
        { word: 'quietly', ko: '조용히' },
        { word: 'surprised', ko: '놀란' },
        { word: 'beautiful', ko: '아름다운' },
      ],
    },
  ],

  5: [
    {
      id: 'g5_01', title: 'The Lost Kitten', titleKo: '길 잃은 아기 고양이',
      sentences: [
        { en: 'On my way home, I heard a soft cry.', ko: '집에 오는 길에, 나는 작은 울음소리를 들었어요.' },
        { en: 'A tiny kitten was hiding under a car.', ko: '작은 아기 고양이가 차 밑에 숨어 있었어요.' },
        { en: 'It looked hungry, scared, and completely alone.', ko: '그것은 배고프고, 무섭고, 완전히 혼자인 것처럼 보였어요.' },
        { en: 'I gently picked it up and held it close.', ko: '나는 조심스럽게 그것을 들어 올려 꼭 안았어요.' },
        { en: 'My family and I decided to take care of it.', ko: '우리 가족과 나는 그것을 돌보기로 결정했어요.' },
        { en: 'Now, the kitten happily lives with us.', ko: '이제 그 고양이는 우리와 행복하게 살고 있어요.' },
      ],
      vocab: [
        { word: 'kitten', ko: '아기 고양이' },
        { word: 'hide', ko: '숨다' },
        { word: 'scared', ko: '무서워하는' },
        { word: 'gently', ko: '부드럽게' },
        { word: 'decide', ko: '결정하다' },
        { word: 'alone', ko: '혼자인' },
      ],
    },
    {
      id: 'g5_02', title: 'A Day at the Beach', titleKo: '해변에서의 하루',
      sentences: [
        { en: 'Last summer, my family traveled to the beach.', ko: '지난 여름, 우리 가족은 해변으로 여행을 갔어요.' },
        { en: 'The ocean waves were tall and exciting.', ko: '바다 파도가 높고 신났어요.' },
        { en: 'My brother and I built a huge sandcastle.', ko: '내 남동생과 나는 커다란 모래성을 만들었어요.' },
        { en: 'Suddenly, a big wave washed it away.', ko: '갑자기, 큰 파도가 그것을 쓸어가 버렸어요.' },
        { en: 'We laughed instead of feeling sad.', ko: '우리는 슬퍼하는 대신 웃었어요.' },
        { en: 'It became one of my favorite memories.', ko: '그것은 내가 가장 좋아하는 추억 중 하나가 되었어요.' },
      ],
      vocab: [
        { word: 'ocean', ko: '바다' },
        { word: 'wave', ko: '파도' },
        { word: 'huge', ko: '거대한' },
        { word: 'suddenly', ko: '갑자기' },
        { word: 'memory', ko: '추억, 기억' },
        { word: 'instead', ko: '대신에' },
      ],
    },
    {
      id: 'g5_03', title: 'The New Student', titleKo: '전학생',
      sentences: [
        { en: 'A new student joined our class this week.', ko: '이번 주에 새로운 학생이 우리 반에 왔어요.' },
        { en: 'Her name is Sora, and she moved from another city.', ko: '그녀의 이름은 소라이고, 다른 도시에서 이사 왔어요.' },
        { en: 'At first, she looked nervous and quiet.', ko: '처음에, 그녀는 긴장하고 조용해 보였어요.' },
        { en: 'I sat next to her and started a conversation.', ko: '나는 그녀 옆에 앉아 대화를 시작했어요.' },
        { en: 'We discovered that we both love drawing.', ko: '우리는 둘 다 그림 그리기를 좋아한다는 것을 알게 되었어요.' },
        { en: 'By lunchtime, we had become good friends.', ko: '점심시간쯤엔, 우리는 좋은 친구가 되어 있었어요.' },
      ],
      vocab: [
        { word: 'join', ko: '합류하다' },
        { word: 'nervous', ko: '긴장한' },
        { word: 'conversation', ko: '대화' },
        { word: 'discover', ko: '알아내다, 발견하다' },
        { word: 'draw', ko: '그리다' },
        { word: 'lunchtime', ko: '점심시간' },
      ],
    },
    {
      id: 'g5_04', title: 'The Science Project', titleKo: '과학 프로젝트',
      sentences: [
        { en: 'Our teacher gave us a special science project.', ko: '선생님이 우리에게 특별한 과학 프로젝트를 주셨어요.' },
        { en: 'We had to grow plants under different conditions.', ko: '우리는 다른 조건에서 식물을 길러야 했어요.' },
        { en: 'One plant received sunlight, and another stayed in the dark.', ko: '한 식물은 햇빛을 받았고, 다른 식물은 어둠 속에 있었어요.' },
        { en: 'After two weeks, we compared the results carefully.', ko: '2주 후, 우리는 결과를 신중하게 비교했어요.' },
        { en: 'The plant in the dark grew weak and pale.', ko: '어둠 속의 식물은 약하고 창백하게 자랐어요.' },
        { en: 'We learned how important sunlight is for plants.', ko: '우리는 햇빛이 식물에게 얼마나 중요한지 배웠어요.' },
      ],
      vocab: [
        { word: 'condition', ko: '조건' },
        { word: 'sunlight', ko: '햇빛' },
        { word: 'compare', ko: '비교하다' },
        { word: 'result', ko: '결과' },
        { word: 'weak', ko: '약한' },
        { word: 'important', ko: '중요한' },
      ],
    },
    {
      id: 'g5_05', title: 'Volunteering at the Shelter', titleKo: '보호소 봉사활동',
      sentences: [
        { en: 'Last Saturday, I volunteered at an animal shelter.', ko: '지난 토요일, 나는 동물 보호소에서 봉사활동을 했어요.' },
        { en: 'There were many dogs waiting for a new home.', ko: '새로운 집을 기다리는 강아지들이 많았어요.' },
        { en: 'I helped feed them and clean their cages.', ko: '나는 그들에게 밥을 주고 우리를 청소하는 것을 도왔어요.' },
        { en: 'One little dog kept following me around.', ko: '한 작은 강아지가 계속 나를 따라다녔어요.' },
        { en: 'Its eyes seemed to ask for love and care.', ko: '그 눈은 사랑과 관심을 구하는 것 같았어요.' },
        { en: 'I hope it finds a warm family soon.', ko: '나는 그 강아지가 곧 따뜻한 가족을 찾기를 바라요.' },
      ],
      vocab: [
        { word: 'volunteer', ko: '봉사활동을 하다' },
        { word: 'shelter', ko: '보호소' },
        { word: 'feed', ko: '먹이를 주다' },
        { word: 'follow', ko: '따라가다' },
        { word: 'care', ko: '돌봄, 관심' },
        { word: 'hope', ko: '바라다' },
      ],
    },
    {
      id: 'g5_06', title: 'The Time Capsule', titleKo: '타임캡슐',
      sentences: [
        { en: 'Our class decided to make a time capsule.', ko: '우리 반은 타임캡슐을 만들기로 했어요.' },
        { en: 'Each student wrote a letter to their future self.', ko: '각 학생은 미래의 자신에게 편지를 썼어요.' },
        { en: 'We also added photos and small personal items.', ko: '우리는 사진과 작은 개인 물건들도 넣었어요.' },
        { en: 'We buried the capsule under a tree in the yard.', ko: '우리는 마당의 나무 아래에 캡슐을 묻었어요.' },
        { en: 'We plan to open it again after ten years.', ko: '우리는 10년 후에 그것을 다시 열 계획이에요.' },
        { en: 'I wonder what will change by then.', ko: '나는 그때까지 무엇이 바뀔지 궁금해요.' },
      ],
      vocab: [
        { word: 'capsule', ko: '캡슐' },
        { word: 'future', ko: '미래' },
        { word: 'personal', ko: '개인적인' },
        { word: 'bury', ko: '묻다' },
        { word: 'plan', ko: '계획하다' },
        { word: 'wonder', ko: '궁금해하다' },
      ],
    },
    {
      id: 'g5_07', title: 'A Difficult Test', titleKo: '어려운 시험',
      sentences: [
        { en: 'Last week, I had a very difficult math test.', ko: '지난주, 나는 아주 어려운 수학 시험을 봤어요.' },
        { en: 'I studied hard every night for two weeks.', ko: '나는 2주 동안 매일 밤 열심히 공부했어요.' },
        { en: 'During the test, some questions confused me a lot.', ko: '시험 중, 몇몇 문제가 나를 많이 헷갈리게 했어요.' },
        { en: 'I stayed calm and tried my very best.', ko: '나는 침착함을 유지하고 최선을 다했어요.' },
        { en: 'When the results came out, I felt truly relieved.', ko: '결과가 나왔을 때, 나는 정말 안심이 됐어요.' },
        { en: 'Hard work really does pay off in the end.', ko: '노력은 정말로 결국에는 보상을 받아요.' },
      ],
      vocab: [
        { word: 'difficult', ko: '어려운' },
        { word: 'study', ko: '공부하다' },
        { word: 'confuse', ko: '헷갈리게 하다' },
        { word: 'result', ko: '결과' },
        { word: 'relieved', ko: '안심한' },
        { word: 'effort', ko: '노력' },
      ],
    },
    {
      id: 'g5_08', title: 'The School Newspaper', titleKo: '학교 신문',
      sentences: [
        { en: 'This semester, I joined the school newspaper club.', ko: '이번 학기에, 나는 학교 신문 동아리에 가입했어요.' },
        { en: 'My first job was to interview the new principal.', ko: '내 첫 임무는 새 교장 선생님을 인터뷰하는 것이었어요.' },
        { en: 'I felt nervous, so I prepared many questions.', ko: '나는 긴장돼서, 많은 질문을 준비했어요.' },
        { en: 'The interview went better than I had expected.', ko: '인터뷰는 내가 예상했던 것보다 더 잘 진행됐어요.' },
        { en: 'My article was printed in the next newspaper issue.', ko: '내 기사는 다음 신문 호에 실렸어요.' },
        { en: 'Seeing my name in print made me feel proud.', ko: '인쇄물에서 내 이름을 보는 것은 나를 뿌듯하게 했어요.' },
      ],
      vocab: [
        { word: 'newspaper', ko: '신문' },
        { word: 'interview', ko: '인터뷰하다' },
        { word: 'principal', ko: '교장 선생님' },
        { word: 'expect', ko: '예상하다' },
        { word: 'article', ko: '기사' },
        { word: 'print', ko: '인쇄하다' },
      ],
    },
    {
      id: 'g5_09', title: 'My First Speech', titleKo: '나의 첫 연설',
      sentences: [
        { en: 'I had to give my first speech in front of the school.', ko: '나는 학교 앞에서 첫 연설을 해야 했어요.' },
        { en: 'The topic was about protecting our local river.', ko: '주제는 우리 지역 강을 보호하는 것에 대한 것이었어요.' },
        { en: 'My hands were shaking as I walked to the microphone.', ko: '마이크로 걸어갈 때 내 손은 떨리고 있었어요.' },
        { en: 'I took a deep breath and began speaking slowly.', ko: '나는 숨을 깊이 들이쉬고 천천히 말하기 시작했어요.' },
        { en: 'Everyone listened carefully and clapped at the end.', ko: '모두가 주의 깊게 들었고 끝에 박수를 쳤어요.' },
        { en: 'I realized that courage grows with practice.', ko: '나는 용기는 연습과 함께 자란다는 것을 깨달았어요.' },
      ],
      vocab: [
        { word: 'speech', ko: '연설' },
        { word: 'local', ko: '지역의' },
        { word: 'microphone', ko: '마이크' },
        { word: 'breath', ko: '숨' },
        { word: 'carefully', ko: '주의 깊게' },
        { word: 'courage', ko: '용기' },
      ],
    },
    {
      id: 'g5_10', title: 'The Broken Window', titleKo: '깨진 창문',
      sentences: [
        { en: 'While playing baseball, I accidentally broke a window.', ko: '야구를 하다가, 나는 실수로 창문을 깼어요.' },
        { en: 'My heart was pounding, and I felt very afraid.', ko: '내 심장이 쿵쾅거렸고, 나는 아주 무서웠어요.' },
        { en: 'I decided to tell the truth to my neighbor.', ko: '나는 이웃에게 사실대로 말하기로 했어요.' },
        { en: 'She was surprised but appreciated my honesty.', ko: '그녀는 놀랐지만 내 정직함을 고맙게 여겼어요.' },
        { en: 'I used my saved money to pay for it.', ko: '나는 그것을 물어내기 위해 모아둔 돈을 사용했어요.' },
        { en: 'Being honest felt much better than hiding the truth.', ko: '정직한 것이 진실을 숨기는 것보다 훨씬 기분이 좋았어요.' },
      ],
      vocab: [
        { word: 'accidentally', ko: '실수로' },
        { word: 'pound', ko: '쿵쾅거리다' },
        { word: 'truth', ko: '진실' },
        { word: 'appreciate', ko: '고맙게 여기다' },
        { word: 'honesty', ko: '정직함' },
        { word: 'hide', ko: '숨기다' },
      ],
    },
    {
      id: 'g5_11', title: 'A Trip to the Countryside', titleKo: '시골 나들이',
      sentences: [
        { en: 'Last vacation, we visited my uncle in the countryside.', ko: '지난 방학에, 우리는 시골에 계신 삼촌을 방문했어요.' },
        { en: 'The air felt fresh, clean, and very quiet.', ko: '공기는 신선하고 깨끗하고 아주 조용하게 느껴졌어요.' },
        { en: 'I helped my uncle pick vegetables from his field.', ko: '나는 삼촌이 밭에서 채소를 따는 것을 도왔어요.' },
        { en: 'At night, we could see countless bright stars.', ko: '밤에, 우리는 셀 수 없이 많은 밝은 별들을 볼 수 있었어요.' },
        { en: 'City life never showed me a sky like that.', ko: '도시 생활은 나에게 그런 하늘을 보여준 적이 없었어요.' },
        { en: 'I hope to visit the countryside again soon.', ko: '나는 곧 시골을 다시 방문하고 싶어요.' },
      ],
      vocab: [
        { word: 'countryside', ko: '시골' },
        { word: 'fresh', ko: '신선한' },
        { word: 'vegetable', ko: '채소' },
        { word: 'field', ko: '밭, 들판' },
        { word: 'countless', ko: '셀 수 없이 많은' },
        { word: 'city', ko: '도시' },
      ],
    },
    {
      id: 'g5_12', title: 'The Music Competition', titleKo: '음악 경연대회',
      sentences: [
        { en: 'I entered a piano competition for the first time.', ko: '나는 처음으로 피아노 경연대회에 참가했어요.' },
        { en: 'I practiced the same song hundreds of times.', ko: '나는 같은 곡을 수백 번 연습했어요.' },
        { en: 'Backstage, my hands felt cold and sweaty.', ko: '무대 뒤에서, 내 손은 차갑고 땀에 젖어 있었어요.' },
        { en: 'Once I started playing, my fear slowly disappeared.', ko: '연주를 시작하자, 내 두려움은 천천히 사라졌어요.' },
        { en: 'I did not win first place, but I felt proud.', ko: '나는 1등을 하지는 못했지만, 뿌듯함을 느꼈어요.' },
        { en: 'Trying my best mattered more than winning.', ko: '최선을 다한 것이 이기는 것보다 더 중요했어요.' },
      ],
      vocab: [
        { word: 'competition', ko: '경연대회' },
        { word: 'hundred', ko: '백, 수백' },
        { word: 'backstage', ko: '무대 뒤' },
        { word: 'fear', ko: '두려움' },
        { word: 'disappear', ko: '사라지다' },
        { word: 'matter', ko: '중요하다' },
      ],
    },
    {
      id: 'g5_13', title: 'Learning to Cook', titleKo: '요리 배우기',
      sentences: [
        { en: 'This summer, I decided to learn how to cook.', ko: '이번 여름, 나는 요리하는 법을 배우기로 했어요.' },
        { en: 'My first dish was a simple vegetable soup.', ko: '내 첫 요리는 간단한 채소 수프였어요.' },
        { en: 'I accidentally added too much salt at first.', ko: '나는 처음에 실수로 소금을 너무 많이 넣었어요.' },
        { en: 'My mother laughed kindly and helped me fix it.', ko: '엄마는 친절하게 웃으시며 그것을 고치는 것을 도와주셨어요.' },
        { en: 'After many tries, my soup finally tasted delicious.', ko: '여러 번의 시도 후, 내 수프는 마침내 맛있어졌어요.' },
        { en: 'Now, cooking is one of my favorite hobbies.', ko: '이제, 요리는 내가 가장 좋아하는 취미 중 하나예요.' },
      ],
      vocab: [
        { word: 'dish', ko: '요리, 접시' },
        { word: 'soup', ko: '수프' },
        { word: 'salt', ko: '소금' },
        { word: 'fix', ko: '고치다' },
        { word: 'delicious', ko: '맛있는' },
        { word: 'hobby', ko: '취미' },
      ],
    },
    {
      id: 'g5_14', title: 'The Missing Wallet', titleKo: '잃어버린 지갑',
      sentences: [
        { en: 'On my way to school, I found a wallet on the ground.', ko: '학교 가는 길에, 나는 바닥에서 지갑을 발견했어요.' },
        { en: 'Inside, there was money and an identification card.', ko: '안에는, 돈과 신분증이 있었어요.' },
        { en: 'I thought about keeping the money for a moment.', ko: '나는 잠깐 그 돈을 가질까 생각했어요.' },
        { en: 'But I knew that would not be the right choice.', ko: '하지만 나는 그것이 옳은 선택이 아니라는 것을 알았어요.' },
        { en: 'I brought the wallet straight to the police station.', ko: '나는 지갑을 곧장 경찰서로 가져갔어요.' },
        { en: 'The owner thanked me with a grateful smile.', ko: '주인은 고마운 미소로 나에게 감사해했어요.' },
      ],
      vocab: [
        { word: 'wallet', ko: '지갑' },
        { word: 'identification', ko: '신분 증명' },
        { word: 'moment', ko: '순간' },
        { word: 'choice', ko: '선택' },
        { word: 'police', ko: '경찰' },
        { word: 'grateful', ko: '고마워하는' },
      ],
    },
    {
      id: 'g5_15', title: 'A Rainy Sports Day', titleKo: '비 오는 체육대회',
      sentences: [
        { en: 'Our long-awaited sports day almost got canceled by rain.', ko: '오랫동안 기다린 체육대회가 비 때문에 취소될 뻔했어요.' },
        { en: 'Luckily, the rain stopped just before it started.', ko: '다행히, 시작되기 직전에 비가 그쳤어요.' },
        { en: 'The ground was still wet and a little slippery.', ko: '땅은 여전히 젖어 있었고 조금 미끄러웠어요.' },
        { en: 'During the relay race, I almost slipped and fell.', ko: '계주 경기 중, 나는 거의 미끄러져 넘어질 뻔했어요.' },
        { en: 'Somehow, our team still finished in first place.', ko: '어찌 되었든, 우리 팀은 여전히 1등으로 마쳤어요.' },
        { en: 'It became one of the most exciting days ever.', ko: '그것은 역대 가장 신났던 날 중 하나가 되었어요.' },
      ],
      vocab: [
        { word: 'cancel', ko: '취소하다' },
        { word: 'luckily', ko: '다행히' },
        { word: 'slippery', ko: '미끄러운' },
        { word: 'relay', ko: '계주, 릴레이' },
        { word: 'slip', ko: '미끄러지다' },
        { word: 'somehow', ko: '어떻게든' },
      ],
    },
  ],

  6: [
    {
      id: 'g6_01', title: 'The Science Fair', titleKo: '과학의 날',
      sentences: [
        { en: 'Every year, our school holds a science fair in the fall.', ko: '매년, 우리 학교는 가을에 과학의 날을 열어요.' },
        { en: 'This year, I decided to build a small robot.', ko: '올해, 나는 작은 로봇을 만들기로 결정했어요.' },
        { en: 'I spent weeks researching and testing different designs.', ko: '나는 여러 설계를 조사하고 시험하는 데 몇 주를 보냈어요.' },
        { en: 'At first, the robot kept falling over and failing.', ko: '처음에는, 로봇이 계속 넘어지고 실패했어요.' },
        { en: 'I did not give up and kept improving it.', ko: '나는 포기하지 않고 계속 그것을 개선했어요.' },
        { en: 'On the day of the fair, it finally worked perfectly.', ko: '과학의 날에, 그것은 마침내 완벽하게 작동했어요.' },
        { en: 'I felt proud of my hard work.', ko: '나는 내 노력이 자랑스러웠어요.' },
      ],
      vocab: [
        { word: 'research', ko: '조사하다' },
        { word: 'design', ko: '설계, 디자인' },
        { word: 'fail', ko: '실패하다' },
        { word: 'improve', ko: '개선하다' },
        { word: 'perfectly', ko: '완벽하게' },
        { word: 'proud', ko: '자랑스러운' },
      ],
    },
    {
      id: 'g6_02', title: 'A Letter to My Future Self', titleKo: '미래의 나에게 쓰는 편지',
      sentences: [
        { en: 'Our teacher asked us to write a letter to our future selves.', ko: '선생님은 우리에게 미래의 나에게 편지를 쓰라고 하셨어요.' },
        { en: 'At first, I did not know what to say.', ko: '처음에, 나는 무슨 말을 해야 할지 몰랐어요.' },
        { en: 'Then I began to think about my dreams and goals.', ko: '그러다 나는 내 꿈과 목표에 대해 생각하기 시작했어요.' },
        { en: 'I wrote about becoming a kind and brave person.', ko: '나는 친절하고 용감한 사람이 되는 것에 대해 썼어요.' },
        { en: 'I also promised to never stop learning new things.', ko: '나는 또한 새로운 것을 배우는 것을 절대 멈추지 않겠다고 약속했어요.' },
        { en: 'We will open these letters again after five years.', ko: '우리는 5년 후에 이 편지들을 다시 열어볼 거예요.' },
        { en: 'I am curious about who I will become by then.', ko: '나는 그때쯤 내가 어떤 사람이 되어 있을지 궁금해요.' },
      ],
      vocab: [
        { word: 'future', ko: '미래' },
        { word: 'goal', ko: '목표' },
        { word: 'brave', ko: '용감한' },
        { word: 'promise', ko: '약속하다' },
        { word: 'curious', ko: '궁금한' },
        { word: 'become', ko: '~이 되다' },
      ],
    },
    {
      id: 'g6_03', title: 'The Mountain Hike', titleKo: '산 등반',
      sentences: [
        { en: 'Last weekend, my father and I climbed a nearby mountain.', ko: '지난 주말, 아빠와 나는 근처 산에 올랐어요.' },
        { en: 'The trail was steep, rocky, and quite difficult.', ko: '길은 가파르고, 바위가 많고, 꽤 어려웠어요.' },
        { en: 'Halfway up, my legs felt heavy and tired.', ko: '중간쯤에서, 내 다리는 무겁고 지쳤어요.' },
        { en: 'My father encouraged me to keep going slowly.', ko: '아빠는 천천히 계속 가라고 나를 격려해 주셨어요.' },
        { en: 'When we finally reached the top, the view was breathtaking.', ko: '마침내 정상에 도착했을 때, 경치는 숨이 막힐 정도였어요.' },
        { en: 'All my tiredness disappeared in that moment.', ko: '그 순간 내 모든 피로가 사라졌어요.' },
        { en: 'It taught me that hard effort brings great rewards.', ko: '그것은 나에게 힘든 노력이 큰 보상을 가져다준다는 것을 가르쳐 주었어요.' },
      ],
      vocab: [
        { word: 'trail', ko: '길, 등산로' },
        { word: 'steep', ko: '가파른' },
        { word: 'encourage', ko: '격려하다' },
        { word: 'reach', ko: '도달하다' },
        { word: 'view', ko: '경치, 전망' },
        { word: 'effort', ko: '노력' },
      ],
    },
    {
      id: 'g6_04', title: 'The Debate Club', titleKo: '토론 동아리',
      sentences: [
        { en: 'This year, I joined the school debate club.', ko: '올해, 나는 학교 토론 동아리에 가입했어요.' },
        { en: 'Our first topic was about using smartphones at school.', ko: '우리의 첫 주제는 학교에서 스마트폰을 사용하는 것에 대한 것이었어요.' },
        { en: 'I had to argue against using phones in class.', ko: '나는 수업 중 전화 사용에 반대하는 주장을 해야 했어요.' },
        { en: 'It was hard to organize my thoughts clearly.', ko: '내 생각을 명확하게 정리하는 것이 어려웠어요.' },
        { en: 'My partner and I practiced our speech every day.', ko: '내 짝과 나는 매일 우리의 연설을 연습했어요.' },
        { en: 'During the debate, I felt nervous but confident.', ko: '토론 중에, 나는 긴장했지만 자신감이 있었어요.' },
        { en: 'In the end, our team won the debate.', ko: '결국, 우리 팀이 토론에서 이겼어요.' },
      ],
      vocab: [
        { word: 'debate', ko: '토론' },
        { word: 'topic', ko: '주제' },
        { word: 'argue', ko: '주장하다' },
        { word: 'organize', ko: '정리하다' },
        { word: 'practice', ko: '연습하다' },
        { word: 'confident', ko: '자신감 있는' },
      ],
    },
    {
      id: 'g6_05', title: 'Moving to a New City', titleKo: '새로운 도시로 이사',
      sentences: [
        { en: 'Last month, my family moved to a completely new city.', ko: '지난달, 우리 가족은 완전히 새로운 도시로 이사했어요.' },
        { en: 'I had to leave all my old friends behind.', ko: '나는 예전 친구들을 모두 두고 떠나야 했어요.' },
        { en: 'On my first day at the new school, I felt lonely.', ko: '새 학교 첫날, 나는 외로움을 느꼈어요.' },
        { en: 'A kind classmate noticed and sat beside me.', ko: '친절한 반 친구가 알아채고 내 옆에 앉았어요.' },
        { en: 'We talked about our favorite books and games.', ko: '우리는 좋아하는 책과 게임에 대해 이야기했어요.' },
        { en: 'Slowly, this new city started to feel like home.', ko: '천천히, 이 새로운 도시가 집처럼 느껴지기 시작했어요.' },
        { en: 'I realized that new beginnings are not always scary.', ko: '나는 새로운 시작이 항상 무서운 것은 아니라는 것을 깨달았어요.' },
      ],
      vocab: [
        { word: 'completely', ko: '완전히' },
        { word: 'lonely', ko: '외로운' },
        { word: 'notice', ko: '알아차리다' },
        { word: 'classmate', ko: '반 친구' },
        { word: 'slowly', ko: '천천히' },
        { word: 'realize', ko: '깨닫다' },
      ],
    },
    {
      id: 'g6_06', title: 'The Group Project', titleKo: '조별 과제',
      sentences: [
        { en: 'Our teacher assigned us a difficult group project.', ko: '선생님은 우리에게 어려운 조별 과제를 내주셨어요.' },
        { en: 'At first, my group members disagreed about almost everything.', ko: '처음에, 우리 조원들은 거의 모든 것에 대해 의견이 달랐어요.' },
        { en: 'We argued about which topic to choose for days.', ko: '우리는 며칠 동안 어떤 주제를 고를지 다퉜어요.' },
        { en: 'Finally, we decided to listen to each other more carefully.', ko: '마침내, 우리는 서로의 말을 더 주의 깊게 듣기로 했어요.' },
        { en: 'Slowly, we combined our different ideas into one plan.', ko: '천천히, 우리는 서로 다른 생각들을 하나의 계획으로 합쳤어요.' },
        { en: 'Our presentation turned out better than anyone expected.', ko: '우리 발표는 누구도 예상하지 못했던 것보다 더 좋게 나왔어요.' },
        { en: 'I learned that teamwork requires patience and respect.', ko: '나는 팀워크에는 인내와 존중이 필요하다는 것을 배웠어요.' },
      ],
      vocab: [
        { word: 'assign', ko: '(과제 등을) 내주다' },
        { word: 'disagree', ko: '의견이 다르다' },
        { word: 'combine', ko: '합치다' },
        { word: 'presentation', ko: '발표' },
        { word: 'patience', ko: '인내' },
        { word: 'respect', ko: '존중' },
      ],
    },
    {
      id: 'g6_07', title: 'A Difficult Decision', titleKo: '어려운 결정',
      sentences: [
        { en: 'I had to choose between two after-school clubs.', ko: '나는 두 개의 방과 후 동아리 중 하나를 골라야 했어요.' },
        { en: 'One was the science club, which I truly enjoyed.', ko: '하나는 과학 동아리였는데, 나는 그것을 정말 좋아했어요.' },
        { en: 'The other was the soccer team, where my friends played.', ko: '다른 하나는 축구팀이었는데, 내 친구들이 그곳에서 뛰었어요.' },
        { en: 'I made a list of reasons for each choice.', ko: '나는 각 선택에 대한 이유들을 목록으로 만들었어요.' },
        { en: 'After thinking carefully, I chose the science club.', ko: '신중하게 생각한 후, 나는 과학 동아리를 선택했어요.' },
        { en: 'I decided to follow my true interest, not just my friends.', ko: '나는 그저 친구들이 아니라 나의 진짜 관심사를 따르기로 했어요.' },
        { en: 'Looking back, I am glad I made that choice.', ko: '돌아보면, 나는 그 선택을 한 것이 기뻐요.' },
      ],
      vocab: [
        { word: 'choose', ko: '선택하다' },
        { word: 'reason', ko: '이유' },
        { word: 'carefully', ko: '신중하게' },
        { word: 'interest', ko: '관심, 흥미' },
        { word: 'follow', ko: '따르다' },
        { word: 'glad', ko: '기쁜' },
      ],
    },
    {
      id: 'g6_08', title: 'The Election Speech', titleKo: '선거 연설',
      sentences: [
        { en: 'I decided to run for student council president.', ko: '나는 학생회장 선거에 출마하기로 했어요.' },
        { en: 'Writing my campaign speech took several long nights.', ko: '선거 연설을 쓰는 데는 여러 밤이 걸렸어요.' },
        { en: 'I wanted to promise things I could truly keep.', ko: '나는 정말로 지킬 수 있는 것들을 약속하고 싶었어요.' },
        { en: 'On election day, my legs felt weak with nervousness.', ko: '선거일에, 긴장감으로 내 다리가 후들거렸어요.' },
        { en: "I spoke slowly and looked at my classmates' faces.", ko: '나는 천천히 말했고 반 친구들의 얼굴을 봤어요.' },
        { en: 'When the results were announced, I had actually won.', ko: '결과가 발표됐을 때, 나는 실제로 당선됐어요.' },
        { en: 'I promised myself to work hard for everyone.', ko: '나는 모두를 위해 열심히 일하겠다고 스스로에게 약속했어요.' },
      ],
      vocab: [
        { word: 'campaign', ko: '선거 운동' },
        { word: 'promise', ko: '약속하다' },
        { word: 'nervousness', ko: '긴장' },
        { word: 'announce', ko: '발표하다' },
        { word: 'actually', ko: '실제로' },
        { word: 'council', ko: '위원회, 회의' },
      ],
    },
    {
      id: 'g6_09', title: 'Learning from Failure', titleKo: '실패에서 배우기',
      sentences: [
        { en: 'I entered a national writing contest last spring.', ko: '나는 지난 봄에 전국 글쓰기 대회에 참가했어요.' },
        { en: 'I spent weeks writing and rewriting my story.', ko: '나는 몇 주 동안 내 이야기를 쓰고 또 고쳐 썼어요.' },
        { en: 'Unfortunately, my story did not win any prize.', ko: '안타깝게도, 내 이야기는 어떤 상도 받지 못했어요.' },
        { en: 'At first, I felt disappointed and wanted to quit writing.', ko: '처음에는, 나는 실망했고 글쓰기를 그만두고 싶었어요.' },
        { en: 'My teacher told me that failure is part of growth.', ko: '선생님은 실패는 성장의 일부라고 말씀해 주셨어요.' },
        { en: "I read the judges' comments and tried to improve.", ko: '나는 심사위원들의 의견을 읽고 개선하려고 노력했어요.' },
        { en: 'The next year, I finally won second place.', ko: '다음 해에, 나는 마침내 2등을 했어요.' },
      ],
      vocab: [
        { word: 'contest', ko: '대회' },
        { word: 'unfortunately', ko: '안타깝게도' },
        { word: 'disappointed', ko: '실망한' },
        { word: 'quit', ko: '그만두다' },
        { word: 'growth', ko: '성장' },
        { word: 'improve', ko: '개선하다' },
      ],
    },
    {
      id: 'g6_10', title: 'The Environmental Campaign', titleKo: '환경 캠페인',
      sentences: [
        { en: 'Our club started a campaign to reduce plastic waste.', ko: '우리 동아리는 플라스틱 쓰레기를 줄이기 위한 캠페인을 시작했어요.' },
        { en: 'We made posters and hung them around the school.', ko: '우리는 포스터를 만들어 학교 곳곳에 붙였어요.' },
        { en: 'We also asked students to bring their own water bottles.', ko: '우리는 또한 학생들에게 자기 물병을 가져오라고 요청했어요.' },
        { en: 'Some students ignored us, which felt quite discouraging.', ko: '몇몇 학생들은 우리를 무시했는데, 그것은 꽤 낙담스러웠어요.' },
        { en: 'However, many others slowly began to change their habits.', ko: '하지만, 다른 많은 학생들이 천천히 습관을 바꾸기 시작했어요.' },
        { en: 'After one month, plastic waste decreased noticeably.', ko: '한 달 후, 플라스틱 쓰레기가 눈에 띄게 줄었어요.' },
        { en: 'Small actions, we learned, can create a real difference.', ko: '작은 행동들이 진짜 변화를 만들 수 있다는 것을 우리는 배웠어요.' },
      ],
      vocab: [
        { word: 'reduce', ko: '줄이다' },
        { word: 'waste', ko: '쓰레기' },
        { word: 'ignore', ko: '무시하다' },
        { word: 'discouraging', ko: '낙담시키는' },
        { word: 'habit', ko: '습관' },
        { word: 'decrease', ko: '줄다' },
      ],
    },
    {
      id: 'g6_11', title: 'A Memorable Summer', titleKo: '기억에 남는 여름',
      sentences: [
        { en: 'This summer, my family traveled to a small island.', ko: '이번 여름, 우리 가족은 작은 섬으로 여행을 갔어요.' },
        { en: 'We stayed in a tiny house near the sea.', ko: '우리는 바다 근처의 작은 집에서 머물렀어요.' },
        { en: 'Every morning, I woke up to the sound of waves.', ko: '매일 아침, 나는 파도 소리에 잠에서 깼어요.' },
        { en: 'I learned to fish with my grandfather for the first time.', ko: '나는 처음으로 할아버지와 함께 낚시하는 법을 배웠어요.' },
        { en: 'At night, we sat outside and talked for hours.', ko: '밤에는, 우리는 밖에 앉아 몇 시간 동안 이야기했어요.' },
        { en: 'Without phones, our conversations felt deeper and warmer.', ko: '휴대폰 없이, 우리의 대화는 더 깊고 따뜻하게 느껴졌어요.' },
        { en: 'That simple summer became my favorite memory ever.', ko: '그 소박한 여름은 내가 가장 좋아하는 추억이 되었어요.' },
      ],
      vocab: [
        { word: 'island', ko: '섬' },
        { word: 'sea', ko: '바다' },
        { word: 'wave', ko: '파도' },
        { word: 'fish', ko: '낚시하다' },
        { word: 'conversation', ko: '대화' },
        { word: 'memory', ko: '추억, 기억' },
      ],
    },
    {
      id: 'g6_12', title: 'Helping at the Family Store', titleKo: '가게 일 돕기',
      sentences: [
        { en: "During vacation, I helped at my parents' small store.", ko: '방학 동안, 나는 부모님의 작은 가게에서 일을 도왔어요.' },
        { en: 'At first, I found the work boring and repetitive.', ko: '처음에, 나는 그 일이 지루하고 반복적이라고 느꼈어요.' },
        { en: 'Slowly, I began talking with the regular customers.', ko: '천천히, 나는 단골 손님들과 대화를 나누기 시작했어요.' },
        { en: 'I realized how hard my parents worked every single day.', ko: '나는 부모님이 매일 얼마나 열심히 일하시는지 깨달았어요.' },
        { en: 'One busy afternoon, I handled a difficult customer well.', ko: '어느 바쁜 오후, 나는 까다로운 손님을 잘 응대했어요.' },
        { en: 'My parents thanked me and looked genuinely proud.', ko: '부모님은 나에게 고마워하셨고 진심으로 뿌듯해 보이셨어요.' },
        { en: 'I gained a deeper respect for their daily effort.', ko: '나는 부모님의 매일의 노력에 더 깊은 존경심을 갖게 됐어요.' },
      ],
      vocab: [
        { word: 'repetitive', ko: '반복적인' },
        { word: 'customer', ko: '손님' },
        { word: 'handle', ko: '처리하다, 다루다' },
        { word: 'genuinely', ko: '진심으로' },
        { word: 'gain', ko: '얻다' },
        { word: 'daily', ko: '매일의' },
      ],
    },
    {
      id: 'g6_13', title: 'Overcoming Stage Fright', titleKo: '무대 공포 극복하기',
      sentences: [
        { en: 'I have always been terribly afraid of speaking in public.', ko: '나는 항상 사람들 앞에서 말하는 것을 몹시 무서워했어요.' },
        { en: 'This year, I was chosen to host the school assembly.', ko: '올해, 나는 학교 조회를 진행하도록 선택됐어요.' },
        { en: 'I wanted to refuse, but my teacher encouraged me strongly.', ko: '나는 거절하고 싶었지만, 선생님이 강하게 격려해 주셨어요.' },
        { en: 'I practiced in front of a mirror every single day.', ko: '나는 매일 거울 앞에서 연습했어요.' },
        { en: 'On the actual day, my voice trembled at first.', ko: '실제 당일에, 내 목소리는 처음에 떨렸어요.' },
        { en: 'Gradually, I relaxed and spoke with more confidence.', ko: '점차, 나는 긴장을 풀고 더 자신감 있게 말했어요.' },
        { en: 'Facing my fear taught me to believe in myself.', ko: '두려움을 마주한 것은 나 자신을 믿는 법을 가르쳐 줬어요.' },
      ],
      vocab: [
        { word: 'terribly', ko: '몹시, 심하게' },
        { word: 'host', ko: '진행하다' },
        { word: 'refuse', ko: '거절하다' },
        { word: 'tremble', ko: '떨리다' },
        { word: 'gradually', ko: '점차' },
        { word: 'confidence', ko: '자신감' },
      ],
    },
    {
      id: 'g6_14', title: 'The History Project', titleKo: '역사 프로젝트',
      sentences: [
        { en: 'For history class, I interviewed my grandfather about the past.', ko: '역사 수업을 위해, 나는 할아버지께 과거에 대해 인터뷰했어요.' },
        { en: 'He told me stories I had never heard before.', ko: '할아버지는 내가 한 번도 들어본 적 없는 이야기들을 해주셨어요.' },
        { en: 'He described how different daily life used to be.', ko: '그는 예전의 일상생활이 얼마나 달랐는지 설명해 주셨어요.' },
        { en: 'I recorded his voice and wrote everything down carefully.', ko: '나는 할아버지의 목소리를 녹음하고 모든 것을 신중하게 적었어요.' },
        { en: 'While listening, I felt closer to him than ever.', ko: '들으면서, 나는 그 어느 때보다 할아버지와 가까워졌다고 느꼈어요.' },
        { en: 'My final report received the highest grade in class.', ko: '내 최종 보고서는 반에서 가장 높은 점수를 받았어요.' },
        { en: 'More importantly, I gained a treasured family memory.', ko: '더 중요하게, 나는 소중한 가족의 추억을 얻었어요.' },
      ],
      vocab: [
        { word: 'past', ko: '과거' },
        { word: 'describe', ko: '설명하다, 묘사하다' },
        { word: 'record', ko: '녹음하다' },
        { word: 'closer', ko: '더 가까운' },
        { word: 'report', ko: '보고서' },
        { word: 'treasured', ko: '소중한' },
      ],
    },
    {
      id: 'g6_15', title: 'A Letter of Apology', titleKo: '사과 편지',
      sentences: [
        { en: 'Last month, I said something unkind to my best friend.', ko: '지난달, 나는 가장 친한 친구에게 못된 말을 했어요.' },
        { en: 'She stopped talking to me, and I felt terrible.', ko: '그녀는 나에게 말을 걸지 않았고, 나는 기분이 끔찍했어요.' },
        { en: 'I tried apologizing in person, but the words would not come out.', ko: '나는 직접 사과하려 했지만, 말이 나오지 않았어요.' },
        { en: 'So, I decided to write her an honest letter instead.', ko: '그래서, 나는 대신 그녀에게 솔직한 편지를 쓰기로 했어요.' },
        { en: 'I explained my feelings and admitted that I was wrong.', ko: '나는 내 감정을 설명하고 내가 틀렸다는 것을 인정했어요.' },
        { en: 'The next day, she smiled and forgave me completely.', ko: '다음 날, 그녀는 웃으며 나를 완전히 용서해 줬어요.' },
        { en: 'I learned that honest words can heal a broken friendship.', ko: '나는 솔직한 말이 깨진 우정을 치유할 수 있다는 것을 배웠어요.' },
      ],
      vocab: [
        { word: 'unkind', ko: '불친절한, 못된' },
        { word: 'terrible', ko: '끔찍한' },
        { word: 'apologize', ko: '사과하다' },
        { word: 'admit', ko: '인정하다' },
        { word: 'forgive', ko: '용서하다' },
        { word: 'heal', ko: '치유하다' },
      ],
    },
  ],
};
